### ISSUE TITLE
Problem with reactivity using prop enabled

### ISSUE THREAD

**Issue by danielperez9430** [thecodewarrior/Tippy.vue#1]
I need to show or hide the tippy tooltips conditional, in my case I use a prop with the name "collapse" that is a boolean value.

So I v-bind the prop to the enabled tippy.vue prop that I change the value from true/false, but in the end the tippy.vue don't follow the reactivity. So, only if I reload the page I can get tippy hide or not.

Example:

```vue
<template>
  <tippy-singleton
    delay="200"
    placement="right"
    moveTransition="transform 0.2s ease-out"
    :enabled="collapse"
  />

  <ComponentX v-tippy />
  <tippy singleton>{{ __("Search") }}</tippy>
  <ComponentY v-tippy />
  <tippy singleton>{{ __("Go Back") }}</tippy>
</template>
<script setup>
const props = defineProps({
  collapse: { type: Boolean, default: true }
})
</script>
```

**Comment by thecodewarrior** [comment]
I just threw together a test with your code and it seems to be working fine:

https://user-images.githubusercontent.com/5467669/155257479-bdf40dee-6d23-4024-814c-4b7e58846045.mov

The one thing that may not be intuitive is that re-enabling the tooltip won't make it pop up, you need to move your cursor off and back on.

**Comment by danielperez9430** [comment]
Oh my bad, sorry @thecodewarrior I put bad the name of the prop in the component ("enable" -> "enabled") this is why don't work works for me 😕  But now I fix it. Thanks for your time 👍
