### ISSUE TITLE
Tippy as component

### ISSUE THREAD

**Issue by Kcko** [thecodewarrior/Tippy.vue#4]
Hi,

tippy as a directive works fine, but when i try to use like a component Im getting this error 
![](https://bit.ly/3Jc14LG)  
![](https://bit.ly/36gbBaa)

where is the problem please? Im using vue version 3.0.11

I registered tippy as a directive and component

```
import { TippyDirective, Tippy, TippySingleton } from 'tippy.vue'
    context.vueApp.directive('tippy', TippyDirective)
    context.vueApp.component('tippy', Tippy)
    context.vueApp.component('tippy-singleton', TippySingleton)
 ```

**Comment by Kcko** [comment]
In version 3.0.0 this works. Not in version 3.1.2. I'm researching the differences in dependencies (package.json) and I don't see anything fundamental, I'm confused, where is the problem, please?


- https://github.com/thecodewarrior/Tippy.vue/blob/v3.0.0/package.json  (3.0.0)
- https://github.com/thecodewarrior/Tippy.vue/blob/v3.1.2/package.json (3.1.2)

**Comment by Kcko** [comment]
I  just updated back to a higher version (3.1.2) and still works ... I dont really understand this strange NPM fuc**** behavior.  Something strange between  heaven and earth.

**Comment by Kcko** [comment]
I have to confirm, that 3.0.0 working ... 3.1.2 none, can you tell me how check whats changed a where is the problem?

**Comment by thecodewarrior** [comment]
Between 3.0.0 and 3.1.2 I did a major internal refactor to support custom properties. I can't reproduce your issue, so a bit more information would be helpful. 

1. Are you using Tippy.vue in a project with webpack and such, or are you using it in-browser with a CDN?
2. Is your code somewhere I can view it? That would help immensely in trying to reproduce the issue.
3. It would be very helpful if you could add a breakpoint and record state of `props` on that line. Something like this:
![image](https://user-images.githubusercontent.com/5467669/159131896-8e516642-cc19-4a98-a784-f5991d9b8c4b.png)
